version: '3'
services:
  producer:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "9092:9092"
    networks:
      - net

volumes:
  postgres:
    driver: local

networks:
  net: