FROM python:3.6

RUN apt-get update \
    && rm -rf /var/lib/apt/lists/*

RUN pip3 install --upgrade pip \
    opencv-python

RUN pip3 install pandas \
    matplotlib \
    PyYAML \
    requests \
    scipy \
    tqdm \
    tensorboard \
    seaborn

RUN pip3 install scikit-learn