version: '3'
services:
  producer:
    platform: linux/amd64
    build:
      context: .
      dockerfile: Dockerfile
    networks:
      - net

volumes:
  postgres:
    driver: local

networks:
  net: