version: '3'

services:
  jetson-pod:
    image: fxdros/fogverse-smart-ads:cpu-jetson
    volumes:
      - ./logs/:/app/logs/
    restart: always
    deploy:
      resources:
        limits:
          cpus: '0.75'
          memory: 2800M