version: '3'

services:
  cloud-pod:
    image: fxdros/fogverse-smart-ads:input-jetson
    volumes:
      - ./logs/:/app/logs/
    restart: always
    deploy:
      resources:
        limits:
          cpus: '0.75'
          memory: 500M